services:
  listener:
    build: ./listener
    network_mode: 'host'
    environment:
      - REDIS_URL=${REDIS_URL}
      - BLUESKY_IDENT=${BLUESKY_IDENT}
      - BLUESKY_PASS=${BLUESKY_PASS}
      - DOODLE_POLLING_FREQ_SECONDS=120
    restart: unless-stopped

  frontend:
    build: ./frontend
    network_mode: 'host'
    environment:
      - REDIS_URL=${REDIS_URL}
    restart: unless-stopped

