services:
  listener:
    build: ./listener
    environment:
      - REDIS_URL=${REDIS_URL}
      - BLUESKY_IDENT=${BLUESKY_IDENT}
      - BLUESKY_PASS=${BLUESKY_PASS}
      - DOODLE_POLLING_FREQ_SECONDS=120
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=${REDIS_URL}
    restart: unless-stopped

